name: Deploy CI/CD

on:
    workflow_dispatch:
    push:
        branches: ["deploy"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push register app
              uses: docker/build-push-action@v3
              with:
                  context: ./api
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/mensa-stats:latest

            - name: Pterodactyl-Restart (Deploy to prod)
              uses: hwalker928/ptero-gitsync@v1.0
              with:
                  panel-url: ${{ secrets.PTE_PANEL_URL }}
                  api-key: ${{ secrets.PTE_BEARER_TOKEN }}
                  server-id: ${{ secrets.PTE_PANEL_ID }}
